### ISSUE TITLE
iTunesRichPresence for MAC!?!?!

### ISSUE THREAD

**Issue by ClassifiedDuck** [nint8835/iTunesRichPresence#81] opened 2021-03-02 16:10 UTC
Hello! I was wondering if you could make a version for Mac?!?!

**Comment by nint8835** [comment] 2021-03-02 16:14
Duplicate of #68, #37, #23

As noted in the readme, there are currently no plans for a macOS version of the app. There is an existing issue (#68) open tracking this feature request.

**Closed as completed by nint8835** 2021-03-02 16:14 UTC
Labels: duplicate, enhancement

**Comment by ClassifiedDuck** [comment] 2021-03-02 16:27
Okay, thank you! I gave you the new logo here,
https://github.com/nint8835/iTunesRichPresence/issues/79
