### ISSUE TITLE
Get Album Art from iTunes Track, set as Thumbnail for Now Playing

### ISSUE THREAD

**Issue by ghost** [nint8835/iTunesRichPresence#24] opened 2018-10-02 18:59 UTC
Hello,

Is there any way to implement album art from iTunes into the now playing box on Discord, instead of just the iTunes icon for every song?

Thanks

**Comment by nint8835** [comment] 2018-10-02 19:20
Duplicate of issue #22 and issue #18.

**Closed as completed by nint8835** 2018-10-02 19:20 UTC
Labels: enhancement, wontfix
