### ISSUE TITLE
Song artwork?

### ISSUE THREAD

**Issue by ReubenBTalbott** [nint8835/iTunesRichPresence#22] opened 2018-08-18 22:54 UTC
Is it possible to make discord show the song artwork?

**Comment by nint8835** [comment] 2018-08-18 22:56
Duplicate of issue #18. With the way Rich Presence currently works, cover art is not really possible.

**Closed as completed by nint8835** 2018-08-18 22:56 UTC
Labels: enhancement, wontfix

**Comment by ReubenBTalbott** [comment] 2018-08-18 23:12
Thanks for the reply
