### ISSUE TITLE
AVG Flags New Versions of iTunesRichPresence as Hazardous

### ISSUE THREAD

**Issue by travilist** [nint8835/iTunesRichPresence#19] opened 2018-07-02 15:32 UTC
When opening iTunesRichPresence version 2.1.0, AVG immediately flags it as a threat and moves it to quarantine unless a specific exception is created for the .exe file.

(Images attached using Imgur)
 Upon opening iTunesRichPresence-Rewrite.exe - https://i.imgur.com/5iDYkLJ.png
 AVG CyberCapture monitoring the application - https://i.imgur.com/0JU5Nok.png
 AVG moving the .exe to quarantine - https://i.imgur.com/imTXRY5.png
 AVG attempted identification of the file - https://i.imgur.com/IBYy5fK.png
 (Upon selecting 'I trust this file' permission to open iTRP is denied.)

AVG Information:
Internet Security 2018
Version 18.5.3059 (6/20/2018)
Definitions Version 180702-2 (7/2/2018)

**Comment by nint8835** [comment] 2018-07-02 15:40
Hey, thanks for reporting the issue! AVG and Avast are effectively the same thing at this point (they are the same company), so this is a duplicate of #16. When that issue is fixed, this one should be fixed as well.

**Closed as completed by nint8835** 2018-07-02 15:40 UTC
Labels: bug, duplicate
