### ISSUE TITLE
Album Artwork

### ISSUE THREAD

**Issue by jeikob** [nint8835/iTunesRichPresence#28] opened 2018-12-02 06:29 UTC
Love this application! I was just wondering if it would be possible to display album artwork on the rich presence panel when you click on someone's name instead of just the iTunes icon.

I know that there is a way to set a custom image for this, but I'm not so sure about how to do this dynamically. There must be a way though seeing as though when you play a game like League of Legends it actually displays the Champion you're playing as in the picture. For the native Spotify integration they are able to do this as well.

So, with all that being said, I wonder if that would be possible to do with this iTunes version.
Thanks for the amazing work on this fun little application. 👍

**Comment by nint8835** [comment] 2018-12-02 06:33
Duplicate of #24, #22, #18. Not possible as you are only able to use 100 images that you have uploaded to the discord site. League works because they have fewer images than that, and Spotify works because it is officially developed by discord and Spotify Devs so it has special abilities.

**Closed as completed by nint8835** 2018-12-02 06:33 UTC
Labels: duplicate, enhancement, wontfix
