### ISSUE TITLE
A few feature requests, if possible.

### ISSUE THREAD

**Issue by yagiz-dev** [nint8835/iTunesRichPresence#74] opened 2020-10-25 09:47 UTC
It'd be cool to have album covers being RPC thumbnail, instead of the iTunes logo, like how it is in Spotify.

Also, while it's "Playing Apple Music" in user status, it's "Listening Spotify" in the official Spotify integration. You could change the action from "playing" to "listening", if possible. It'd look better.

**Comment by nint8835** [comment] 2020-10-26 10:49
Unfortunately, both of the things you suggested have been suggested previously and are not possible. In the event they become possible I'll definitely look into implementing them though.

Album art: Duplicate of #24, #22, #18 
Listening: Duplicate of #70, #9

**Closed as completed by nint8835** 2020-10-26 10:49 UTC
Labels: invalid, wontfix
